// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqaIiZaj4K_ZLbm1Ydle9c11jWRSXqCUU',
    appId: '1:722675635524:web:2018b15ae386f3efb5f311',
    messagingSenderId: '722675635524',
    projectId: 'note-search-g',
    authDomain: 'note-search-g.firebaseapp.com',
    storageBucket: 'note-search-g.firebasestorage.app',
    measurementId: 'G-N72WNGGBGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2VSjmsEz2m_zeAiVZZ_Jd3MZ3LBs-ck4',
    appId: '1:722675635524:android:3d88b60e84fa66c1b5f311',
    messagingSenderId: '722675635524',
    projectId: 'note-search-g',
    storageBucket: 'note-search-g.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-fqw_6zredf9i4nPIGYVrZ0ROKnfT888',
    appId: '1:722675635524:ios:fc9ddc594cbb6288b5f311',
    messagingSenderId: '722675635524',
    projectId: 'note-search-g',
    storageBucket: 'note-search-g.firebasestorage.app',
    iosBundleId: 'com.galileo.notesearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-fqw_6zredf9i4nPIGYVrZ0ROKnfT888',
    appId: '1:722675635524:ios:fc9ddc594cbb6288b5f311',
    messagingSenderId: '722675635524',
    projectId: 'note-search-g',
    storageBucket: 'note-search-g.firebasestorage.app',
    iosBundleId: 'com.galileo.notesearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqaIiZaj4K_ZLbm1Ydle9c11jWRSXqCUU',
    appId: '1:722675635524:web:bb61eff40291e432b5f311',
    messagingSenderId: '722675635524',
    projectId: 'note-search-g',
    authDomain: 'note-search-g.firebaseapp.com',
    storageBucket: 'note-search-g.firebasestorage.app',
    measurementId: 'G-G09CNR5T5L',
  );
}
